version: "3.9"
services:

    webgoat:
        container_name: "webgoat"
        image: santosomar/webgoat
        volumes:
          - logs-webgoat:/tmp/
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.11
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true"
                tag: "webgoat"
                
    juice-shop:
        container_name: "juice-shop"
        image: santosomar/juice-shop
        volumes: 
          - logs-juice-shop:/juice-shop/logs/
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.12
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true"        
                tag: "juice-shop"

    dvwa:
        container_name: "dvwa"
        image: santosomar/dvwa
        volumes: 
          - logs-dvwa:/var/log/apache2/
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.13
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true" 
                tag: "dvwa"

    mutillidae_2:
        container_name: "mutillidae_2"
        image: santosomar/mutillidae_2
        volumes:
          - logs-mutillidae_2:/var/log/apache2
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.14
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true" 
                tag: "mutillidae_2"

    dvna:
        container_name: "dvna"
        image: santosomar/dvna
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.15
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true" 
                tag: "dvna"

    hackazon:
        container_name: "hackazon"
        image: santosomar/hackazon
        volumes: 
          - logs-hackazon:/var/log/apache2
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.16
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true" 
                tag: "hackazon"
                
    wp:
        container_name: "wordpress"
        image: wordpress:latest # https://hub.docker.com/_/wordpress/
        restart: unless-stopped
        ports:
            - ${IP}:80:80 # change ip if required
        volumes:
          - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
          - ./wp-app:/var/www/html # Full wordpress project
          #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
          #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_NAME: "${DB_NAME}"
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
        depends_on:
          - db
        links:
          - db
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true"

    wpcli:
        image: wordpress:cli
        container_name: "wordpress_cli"
        restart: unless-stopped
        volumes:
          - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
          - ./wp-app:/var/www/html
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_NAME: "${DB_NAME}"
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
        depends_on:
          - db
          - wp
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true"

    pma:
        image: phpmyadmin/phpmyadmin
        container_name: "phpmyadmin"
        restart: unless-stopped
        environment:
          # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
          PMA_HOST: db
          PMA_PORT: 3306
          MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
          UPLOAD_LIMIT: 50M
        ports:
          - ${IP}:8080:80
        links:
          - db:db
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true"

    db:
        image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
        container_name: "mysql_wp"
        restart: unless-stopped
        ports:
          - ${IP}:3306:3306 # change ip if required
        command: [
            '--default_authentication_plugin=mysql_native_password',
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]
        volumes:
          - ./wp-data:/docker-entrypoint-initdb.d
          - db_data:/var/lib/mysql
        environment:
          MYSQL_DATABASE: "${DB_NAME}"
          MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true"

networks:
    vulnnet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.6.0/24
                  gateway: 10.6.6.1
volumes:
    db_data:
    logs-hackazon:
      external: true
    logs-dvwa:
      external: true
    logs-webgoat:
      external: true
    logs-juice-shop:
      external: true
    logs-mutillidae_2:
      external: true
