version: "3.9"
services:

    webgoat:
        container_name: "webgoat"
        image: santosomar/webgoat
        volumes:
          - logs-webgoat:/tmp/
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.11
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true"
                tag: "webgoat"
                
    juice-shop:
        container_name: "juice-shop"
        image: santosomar/juice-shop
        volumes: 
          - logs-juice-shop:/juice-shop/logs/
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.12
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true"        
                tag: "juice-shop"

    dvwa:
        container_name: "dvwa"
        image: santosomar/dvwa
        volumes: 
          - logs-dvwa:/var/log/apache2/
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.13
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true" 
                tag: "dvwa"

    mutillidae_2:
        container_name: "mutillidae_2"
        image: santosomar/mutillidae_2
        volumes:
          - logs-mutillidae_2:/var/log/apache2
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.14
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true" 
                tag: "mutillidae_2"

    dvna:
        container_name: "dvna"
        image: santosomar/dvna
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.15
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true" 
                tag: "dvna"

    hackazon:
        container_name: "hackazon"
        image: santosomar/hackazon
        volumes: 
          - logs-hackazon:/var/log/apache2
        restart: unless-stopped
        networks:
            vulnnet:
                ipv4_address: 10.6.6.16
        logging:
            driver: splunk
            options:
                splunk-token: "${SPLUNK_TOKEN}"
                splunk-url: "${SPLUNK_URL}"
                splunk-insecureskipverify: "true" 
                tag: "hackazon"

networks:
    vulnnet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.6.0/24
                  gateway: 10.6.6.1
volumes:
    logs-hackazon:
      external: true
    logs-dvwa:
      external: true
    logs-webgoat:
      external: true
    logs-juice-shop:
      external: true
    logs-mutillidae_2:
      external: true
