version: "3.9"
services:

    webgoat:
        container_name: "webgoat"
        image: santosomar/webgoat
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.11
        logging:
            driver: splunk
            options:
                splunk-token: "88136f63-c850-47d9-984b-2cc21f622940"
                splunk-url: "https://192.168.174.137:8088"
                splunk-insecureskipverify: "true"
                
    juice-shop:
        container_name: "juice-shop"
        image: santosomar/juice-shop
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.12
        logging:
            driver: splunk
            options:
                splunk-token: "88136f63-c850-47d9-984b-2cc21f622940"
                splunk-url: "https://192.168.174.137:8088"
                splunk-insecureskipverify: "true"        
                
    dvwa:
        container_name: "dvwa"
        image: santosomar/dvwa
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.13
        logging:
            driver: splunk
            options:
                splunk-token: "88136f63-c850-47d9-984b-2cc21f622940"
                splunk-url: "https://192.168.174.137:8088"
                splunk-insecureskipverify: "true" 

    mutillidae_2:
        container_name: "mutillidae_2"
        image: santosomar/mutillidae_2
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.14
        logging:
            driver: splunk
            options:
                splunk-token: "88136f63-c850-47d9-984b-2cc21f622940"
                splunk-url: "https://192.168.174.137:8088"
                splunk-insecureskipverify: "true" 

    dvna:
        container_name: "dvna"
        image: santosomar/dvna
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.15
        logging:
            driver: splunk
            options:
                splunk-token: "88136f63-c850-47d9-984b-2cc21f622940"
                splunk-url: "https://192.168.174.137:8088"
                splunk-insecureskipverify: "true" 

    hackazon:
        container_name: "hackazon"
        image: santosomar/hackazon
        restart: unless-stopped
        networks:
            websploit:
                ipv4_address: 10.6.6.16
        logging:
            driver: splunk
            options:
                splunk-token: "88136f63-c850-47d9-984b-2cc21f622940"
                splunk-url: "https://192.168.174.137:8088"
                splunk-insecureskipverify: "true" 


networks:
    websploit:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.6.0/24
                  gateway: 10.6.6.1
