version: "3.7"

services:
  web:
    build: .
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    ports:
      - "4000:4000"
    networks:
          nodegoatnet:
              ipv4_address: 10.6.7.2

  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - 27017
    networks:
          nodegoatnet:
              ipv4_address: 10.6.7.3

networks:
    nodegoatnet:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.7.0/24
                  gateway: 10.6.7.1



